language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: YyqRUhxYED7FhgpWcAtBmTdFXJ6+6ffF71S6Lmq80Wn8wLJKBG4ue2E4sAuPP4VNlNcZOHyYNKbnxoDmfnwGJgsfPddGcf5TmwZOWk0FeVCv4qt7ud9ix4fZTrO1GZpRQ4KgbAmqP4Hyt8QqlDWrU6yIXbClnp6sXKJERDrsnuwwIkeNu8mGRgHUOCS2oDLNh41YgbkpLlXwAVYok61JnDLHXLEwiXMaiigXW6lRn0VYFTDb73kjOQ732fm1wUrPR+sXS5oQB0j2WHZbi1fDxYDpUEOG7UmMilMMfEX8L0IoUkK7p6iDsv87ilulmEoJYbWBwt42OGbmCq48GYvHVLVZQI6Oq6TzdFRMGldjbDko9wjsSdu6pccpYkKS7nqAIcMC58T3+JLz5H4WhilvlbS9iA+IynZ58LpT+KUimVawQUB40yLzbLWBj96+5Q/cECm9BGgsZf2zJcsu+abmgdG/MeWFQ/UhBK5ABSRykUcbANgWGFtNG9WU60e7W+BsNWuXLhIbf2gBYJXV9UYwgNwhbuh7nHOJxUGylez46EnkekBPYMCAjsYv+k4GYR/bMYfSYJVdq2JLnzzWlLa8UTXj0jtJO75q5mE/z5BX5i8Hnnz31ZDqmsKcL2GPYsZQpn00B+HDXWGvTLggd/Ora27fwiWonooYutR6kePWU4k=
  app: protected-falls-55099
  on:
    repo: lbox87/node-shopping-list-integration-tests
